<?php

namespace App\Models;

use App\Helpers\Helper;
use App\Http\Traits\I18n;
use App\Models\AreaGallery;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Http\Controllers\Admin\AdminController;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

class Area extends Model
{
    use HasFactory, SoftDeletes, I18n;

    const DIR = 'area';
    const DIR_GALLERY = 'gallery';

    // cover sizes
    const MAIN_SIZE = 386 . '_';
    const SIZES = [
        [960 => 480],
        [773 => 564],
        [386 => 282],
        [320 => 368],
        [69 => 69],
    ];

    const SIZES_GALLERY = [
        [445 => 621],
        [125 => 175],
    ];

    protected $table = 'areas';

    protected $fillable = [
        'logo',
        'slug',
        'website',
        'social_media_links',
        'contact_phone',
        'contact_email',
        'active',
        'population',
        'area',
        'created_by',
        'updated_by',
    ];

    protected $casts = [
        'social_media_links' => 'array',
    ];

     /**
     * Get the gallery for the municipality.
     *
     * @return HasMany
     */
    public function gallery(): HasMany
    {
        return $this->hasMany(AreaGallery::class);
    }

    /**
     * Retrieves the directory path for the Area model.
     *
     * This method returns the directory path for the Area model. The directory path is constructed based on the ID of the municipality.
     * The directory path is generated by concatenating the main directory path from the AdminController class, the constant DIR from the Municipality class,
     * and the result of dividing the ID of the Area by 1000.
     *
     * @return string The directory path for the Area model.
     */
    public function getDir(): string
    {
        return AdminController::MAIN_DIR . self::DIR . '/' . intval($this->id / 1000) . '/';
    }

    /**
     * Retrieves the logo of the Area.
     *
     * @param int $size The size of the logo. Defaults to 0.
     * @return string The URL of the logo.
     */
    public function getLogo(int $size = 0): string
    {
        if (!$size) {
            $size = self::MAIN_SIZE;
        } else {
            $size = $size . '_';
        }

        return Helper::getLogo($this->logo, $this->getDir(), $size);
    }

    /**
     * Get the URL for the Area.
     *
     * @return string The URL for the Area.
     */
    public function getUrl(): string
    {
        return route('area.show', ['slug' => $this->slug, 'id' => $this->id]);
    }

    /* Admin */
    /**
     * Retrieve all Areas with optional filtering by name.
     *
     * @param Request $request The HTTP request object.
     *
     * @return object The collection of Areas.
     */
    public function getAdminAll(Request $request): object
    {
        $word = $request->get('word');

        $builder = $this->with(['i18n']);

        if ($word) {
            $builder->whereHas('i18n', function ($query) use ($word) {
                $query->where('name', 'like', '%' . $word . '%');
            });
        }

        $builder->orderBy('id', 'desc');

        return $builder->paginate(10);
    }

    /**
     * Retrieve the Areas for the admin select dropdown.
     *
     * @return Collection
     */
    public static function getAreasForSelectAdmin(): Collection
    {
        return self::with(['i18n' => function ($query) {
            $query->select('area_id', 'name')->orderBy('name', 'asc');
        }])
            ->where('active', 1)
            ->whereNull('deleted_at')
            ->orderBy('id', 'desc')
            ->get();
    }

    /**
     * Get the municipalities for the area
     *
     * @return HasMany
     */
    public function municipality(): HasMany
    {
        return $this->hasMany(Municipality::class);
    }

    /**
     * Get the participations for the area
     *
     * @return HasMany
     */
    public function participations(): HasMany
    {
        return $this->hasMany(Participation::class);
    }

    
    /**
     * Get all landmarks from municipalities attached to the area.
     *
     * @return HasManyThrough
     */
    public function landmarks(): HasManyThrough
    {
        return $this->hasManyThrough(Landmark::class, Municipality::class);
    }

    /**
     * Get all news from municipalities attached to the area.
     *
     * @return HasManyThrough
     */
    public function news(): HasManyThrough
    {
        return $this->hasManyThrough(News::class, Municipality::class);
    }
    
    /**
     * Retrieve all active areas.
     *
     * @return Collection
     */
    public static function getActiveAreas(): Collection
    {
        return self::where('active', 1)
            ->whereNull('deleted_at')
            ->orderBy('id', 'desc')
            ->get();
    }

     public function getAllLandmarks(): Collection
    {
        $landmarks = $this->municipality()
        ->with('landmarks')
        ->get()
        ->pluck('landmarks')
        ->flatten();

    return new Collection($landmarks);
    }

    /**
     * Searches for area based on a given word.
     * The search is performed in three stages:
     * 1. Search in the 'name' field.
     * 2. Search in the 'description' field.
     * 3. Search in both 'name' and 'description' fields.
     * 
     * The search word is first converted from Latin to Cyrillic characters.
     * The search is performed using MySQL's full-text search in BOOLEAN MODE.
     * Results are ordered by the length of the matched field(s) in descending order.
     * 
     * @param string $word The search term to look for.
     * @param int $limit The number of results to return per page. Default is 20.
     * @return LengthAwarePaginator Paginated search results.
     */
    public function searchAreas(string $word, int $limit = 20): LengthAwarePaginator
    {
        $word = Helper::latinToCyrillic($word);

        $word = '+' . $word . '*';

        $titleOnly = $this->with(['i18n'])->where('active', 1)->whereHas('i18n', function ($query) use ($word) {
            $query->whereRaw("MATCH(name) AGAINST(? IN BOOLEAN MODE)", [$word])
                ->orderByRaw("LENGTH(name) DESC");
        });

        // $descriptionOnly = $this->with(['i18n'])->where('active', 1)->whereHas('i18n', function ($query) use ($word) {
        //     $query->whereRaw("MATCH(description) AGAINST(? IN BOOLEAN MODE)", [$word])
        //         ->orderByRaw("LENGTH(description) DESC");
        // });

        // $titleAndDescription = $this->with(['i18n'])->where('active', 1)->whereHas('i18n', function ($query) use ($word) {
        //     $query->whereRaw("MATCH(name,description) AGAINST(? IN BOOLEAN MODE)", [$word])
        //         ->orderByRaw("(LENGTH(name) + LENGTH(description)) DESC");
        // });

        $builder = $titleOnly
            // ->union($titleAndDescription)
            // ->union($descriptionOnly)
        ;


        return $builder->paginate($limit);
    }

}