<?php

namespace App\Models;

use App\Helpers\Helper;
use App\Http\Traits\I18n;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Http\Controllers\Admin\AdminController;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Landmark extends Model
{
    use HasFactory, SoftDeletes, I18n;
    
    const DIR = 'landmark'; 
    const DIR_GALLERY = 'gallery';

    // cover sizes
    const MAIN_SIZE = 386 . '_';
    const SIZES = [
        [960 => 480],
        [773 => 564],
        [386 => 282],
        [320 => 368],
        [69 => 69],
    ];

    const SIZES_GALLERY = [
        [445 => 621],
        [125 => 175],
    ];

    protected $table = 'landmarks';

    protected $fillable = [
        'logo',
        'slug',
        'municipality_id',
        'longitude',
        'latitude',
        'working_hours',
        'active_to',
        'created_by',
        'updated_by',
    ];

    protected $casts = [
        'working_hours' => 'array'
    ];

    /**
     * Get the gallery for the landmark.
     *
     * @return HasMany
     */
    public function gallery(): HasMany
    {
        return $this->hasMany(LandmarkGallery::class);
    }

     /**
     * Retrieves the directory path for the landmark model.
     *
     * This method returns the directory path for the landmark model. The directory path is constructed based on the ID of the municipality.
     * The directory path is generated by concatenating the main directory path from the AdminController class, the constant DIR from the Municipality class,
     * and the result of dividing the ID of the landmark by 1000.
     *
     * @return string The directory path for the landmark model.
     */
    public function getDir(): string
    {
        return AdminController::MAIN_DIR . self::DIR . '/' . intval($this->id / 1000) . '/';
    }

    /**
     * Retrieves the logo of the landmark.
     *
     * @param int $size The size of the logo. Defaults to 0.
     * @return string The URL of the logo.
     */
    public function getLogo(int $size = 0): string
    {
        if (!$size) {
            $size = self::MAIN_SIZE;
        } else {
            $size = $size . '_';
        }

        return Helper::getLogo($this->logo, $this->getDir(), $size);
    }

    /**
     * Get the URL for the landmark.
     *
     * @return string The URL for the municipality.
     */
    public function getUrl(): string
    {
        return route('landmarks.show', ['slug' => $this->slug, 'id' => $this->id]);
    }

    /* Admin */
    /**
     * Retrieve all landmark with optional filtering by name.
     *
     * @param Request $request The HTTP request object.
     *
     * @return object The collection of municipalities.
     */
    public function getAdminAll(Request $request): object
    {
        $word = $request->get('word');

        $builder = $this->with(['i18n']);

        if ($word) {
            $builder->whereHas('i18n', function ($query) use ($word) {
                $query->where('name', 'like', '%' . $word . '%');
            });
        }

        $builder->orderBy('id', 'desc');

        return $builder->get();
    }
}