<?php

namespace App\Models;

use App\Helpers\Helper;
use App\Models\Landmark;
use App\Http\Traits\I18n;
use Illuminate\Http\Request;
use App\Models\MunicipalityGallery;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Http\Controllers\Admin\AdminController;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Municipality extends Model
{
    use HasFactory, SoftDeletes, I18n;

    const DIR = 'municipality';
    const DIR_GALLERY = 'gallery';

    // cover sizes
    const MAIN_SIZE = 386 . '_';
    const SIZES = [
        [960 => 480],
        [773 => 564],
        [386 => 282],
        [320 => 368],
        [69 => 69],
    ];

    const SIZES_GALLERY = [
        [445 => 621],
        [125 => 175],
    ];

    protected $table = 'municipalities';

    protected $fillable = [
        'logo',
        'slug',
        'website',
        'contact_email',
        'contact_phone_one',
        'contact_phone_two',
        'longitude',
        'latitude',
        'position',
        'working_hours',
        'social_media_links',
        'area_id',
        'active',
        'active_from',
        'active_to',
        'created_by',
        'updated_by',
    ];

    protected $casts = [
        'working_hours' => 'array',
        'social_media_links' => 'array',
    ];

    /**
     * Get the gallery for the municipality.
     *
     * @return HasMany
     */
    public function gallery(): HasMany
    {
        return $this->hasMany(MunicipalityGallery::class);
    }

    /**
     * Retrieves the directory path for the Municipality model.
     *
     * This method returns the directory path for the Municipality model. The directory path is constructed based on the ID of the municipality.
     * The directory path is generated by concatenating the main directory path from the AdminController class, the constant DIR from the Municipality class,
     * and the result of dividing the ID of the municipality by 1000.
     *
     * @return string The directory path for the Municipality model.
     */
    public function getDir(): string
    {
        return AdminController::MAIN_DIR . self::DIR . '/' . intval($this->id / 1000) . '/';
    }

    /**
     * Retrieves the logo of the municipality.
     *
     * @param int $size The size of the logo. Defaults to 0.
     * @return string The URL of the logo.
     */
    public function getLogo(int $size = 0): string
    {
        if (!$size) {
            $size = self::MAIN_SIZE;
        } else {
            $size = $size . '_';
        }

        return Helper::getLogo($this->logo, $this->getDir(), $size);
    }

    /**
     * Get the URL for the municipality.
     *
     * @return string The URL for the municipality.
     */
    public function getUrl(): string
    {
        return route('minicipilities.show', ['slug' => $this->slug, 'id' => $this->id]);
    }

     /* Admin */
    /**
     * Retrieve all municipalities with optional filtering by name.
     *
     * @param Request $request The HTTP request object.
     *
     * @return object The collection of municipalities.
     */
    public function getAdminAll(Request $request): object
    {
        $word = $request->get('word');

        $builder = $this->with(['i18n']);

        if ($word) {
            $builder->whereHas('i18n', function ($query) use ($word) {
                $query->where('name', 'like', '%' . $word . '%');
            });
        }

        $builder->orderBy('id', 'desc');

        return $builder->get();
    }

    /**
     * Retrieve the municipalities for the admin select dropdown.
     *
     * @return Collection
     */
    public static function getMunicipalitiesForSelectAdmin(): Collection
    {
        return self::with(['i18n' => function ($query) {
            $query->select('municipality_id', 'name')->orderBy('name', 'asc');
        }])
            ->where('active', 1)
            ->whereNull('deleted_at')
            ->orderBy('id', 'desc')
            ->get();
    }

    /**
     * Get the landmarks for the municipality.
     *
     * @return HasMany
     */
    public function landmarks(): HasMany
    {
        return $this->hasMany(Landmark::class);
    }

    /**
     * Retrieve the ID of the related area for a given municipality.
     *
     * @param int $municipalityId The ID of the municipality.
     * @return int The ID of the related area.
     */
    public function getRelatedArea(int $municipalityId): int
    {
        return $this->where('id', $municipalityId)->pluck('area_id', 'id')->first();
    }

    /**
     * Get the municipality that owns the landmark.
     *
     * @return BelongsTo
     */
    public function area(): BelongsTo
    {
        return $this->belongsTo(Area::class, 'area_id');
    }

    public function news() {
        return $this->hasMany(News::class);
    }
    
}